name: hello-pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print SHA and create artifact
        run: |
          echo "Commit SHA: $GITHUB_SHA"
          echo "Hello from Ishara!" > hello-5711.txt

      - uses: actions/upload-artifact@v4
        with:
          name: hello-5711
          path: hello-5711.txt

